#+title: Studio 19: I/O Event Handling

* Contributors
- Jonathan Rodriguez Gomez

* Using select()
Program Output:
#+begin_example
sammy@mac files % ./ex2
test
Input available in STDIN
Input received: test

12
Input available in STDIN
Input received: 12

quit
Input available in STDIN
Input received: quit
Quit command received
#+end_example

* Using select() with INET Server-Client
Client Output:
#+begin_example
sammy@mac files % ./select_client
Connection established
Server FQDN: mac.dhcp.wustl.edu
Server time of day: 1776704232.617814

sammy@mac files % ./select_client
Connection established
Server FQDN: mac.dhcp.wustl.edu
Server time of day: 1776704237.598486

#+end_example

Server Output:
#+begin_example
sammy@mac files % ./select_server
Client connection #0 accepted
Client connection #1 accepted
test
Input available in STDIN
Input received: test

quit
Input available in STDIN
Input received: quit
Quit command received
#+end_example

* Using poll() with INET Server-Client

Client Output:
#+begin_example
sammy@mac files % ./poll_client
Connection established
sammy@mac files % ./poll_client
Connection established
sammy@mac files % ./poll_client quit
Connection established
Issuing quit command
#+end_example

Server Output:
#+begin_example
sammy@mac files % ./poll_server
Client 1: Message 1
Client 1: Message 2
test
Input received from STDIN: test

Client 2: Message 1
Client 2: Message 2
Client 3: Message 1
Client 3: Message 2
Client 3: quit
Quit command received
sammy@mac files % ./poll_server
quit
Input received from STDIN: quit
Quit command received
#+end_example

* Using epoll with Client-Server
Client Output:
#+begin_example
sammy@ramanujan:~/Nextcloud/college/Classes/2026/Spring/CSE4202/studios/cse4202-studio19/files$ ./epoll_client
Connection established
sammy@ramanujan:~/nextcloud/college/classes/2026/spring/cse4202/studios/cse4202-studio19/files$ ./epoll_client
Connection established
#+end_example

Server Output (before STDIN input):
#+begin_example
sammy@ramanujan:~/nextcloud/college/classes/2026/spring/cse4202/studios/cse4202-studio19/files$ ./epoll_server
Input available from Client 1
Client 1 has closed the connection
Input available from Client 2
Client 2 has closed the connection
#+end_example

Server Output (after STDIN input):
#+begin_example
studio19/files$ ./epoll_server
Input available from Client 1
Client 1 has closed the connection
Input available from Client 2
Client 2 has closed the connection

[...]

Input available in STDIN
Input available in STDIN
Input available in STDIN
Input available in STDIN
#+end_example

This happens because unlike the client socket STDIN is not closed after it obtains data. Since the default mode of epoll is level-triggered and the data is not cleaned up epoll keeps creating an EPOLLIN event for STDIN.

** The EPOLLET flag
Client Output:
#+begin_example
sammy@ramanujan:~/Nextcloud/college/Classes/2026/Spring/CSE4202/studios/cse4202-studio19/files$ ./epoll_client
Connection established
sammy@ramanujan:~/Nextcloud/college/Classes/2026/Spring/CSE4202/studios/cse4202-studio19/files$ ./epoll_client
Connection established
#+end_example

Server Output:
#+begin_example
sammy@ramanujan:~/Nextcloud/college/Classes/2026/Spring/CSE4202/studios/cse4202-studio19/files$ ./epoll_server
Input available from Client 1
Client 1 has closed the connection
Input available from Client 2
Client 2 has closed the connection
test
Input available in STDIN
#+end_example

Since the change to a POLLIN state only happens once, we don't see the same behavior with STDIN in this case. As we can see the client socket behaves pretty much the same since we are not reading the data that becomes available.
